; ============================================================
;  TFUNIPAYLOAD01B
;  ATmega1284P + MightyCore
;  - externí oscilátor 8 MHz
;  - UART0 bootloader (Optiboot BIGBOOT)
;  - 2 prostředí: ISP + UART
; ============================================================

[env]
platform = atmelavr
framework = arduino
board = TFUNIPAYLOAD01B
board_dir = boards

; MightyCore
board_build.core = MightyCore
board_build.f_cpu = 8000000L
board_hardware.oscillator = external
board_hardware.uart = uart0
board_hardware.bod = 2.7v
board_hardware.eesave = yes
board_bootloader.type = optiboot

; Build flags
build_flags =
  -DARDUINO_AVR_ATmega1284P

; Knihovny
lib_deps =


; Fuses pro ATmega1284P, 8 MHz ext. krystal, BOD 2.7V, EESAVE, Optiboot BIGBOOT 1024 words
; lfuse 0xF7  - full swing crystal oscillator, no CKDIV8
; hfuse 0xD2  - JTAG off, SPI on, EESAVE, BOOTSZ=01 (1024 words), BOOTRST
; efuse 0xFD  - BOD 2.7V

; =========================
; 1) ISP / STK500 (programátor)
;    Nahraje aplikaci + bootloader + fuses
; =========================
[env:TFUNIPAYLOAD01B_isp]
extends = env

upload_protocol = stk500v2
upload_port = /dev/ttyUSB0
upload_speed = 115200

upload_flags =
  -P/dev/ttyUSB0
  -b115200
  -cstk500v2
  -U flash:w:${platformio.packages_dir}/framework-arduino-avr-mightycore/bootloaders/optiboot_flash/bootloaders/atmega1284p/8000000L/optiboot_flash_atmega1284p_UART0_115200_8000000L_B0_BIGBOOT.hex:i
  -U efuse:w:0xFD:m
  -U hfuse:w:0xD2:m
  -U lfuse:w:0xF7:m


; =========================
; 2) UART bootloader (Optiboot) UART0
; =========================
[env:TFUNIPAYLOAD01B_uart]
extends = env

upload_protocol = arduino
upload_port = /dev/ttyUSB0
upload_speed = 115200

monitor_port = /dev/ttyUSB0
monitor_speed = 115200
